stages:
  - packer
  - docker
  - deploy

variables: 
  IMAGE: proget-hz.lonsid.cn/masa-images/library/daprhandbook:0.1.$CI_PIPELINE_ID


packer:
  image: node:lts-alpine
  stage: packer
  only:
    - branches
  script:
    - npm i
    - npm run build
  artifacts:
    expire_in: 1 day
    paths:
      - ./build


docker:
  image: docker:17.05.0
  stage: docker
  only:
    - branches
  variables:
    DOCKER_HOST: tcp://localhost:2375/
  services:
    - name: proget-hz.lonsid.cn/masa-images/library/docker:17.05.01-dind
  script:
    - docker login -u gitlabci -p gitlabci http://proget-hz.lonsid.cn
    - docker build -t $IMAGE .
    - docker push $IMAGE

deploy:
  image: proget-hz.lonsid.cn/masa-images/library/kubectl:1.17.2-newack
  stage: deploy
  only:
    - branches
  script:
    - kubectl set image deployment/daprhandbook daprhandbook=$IMAGE -n masa-preview
